services:
  db:
    image: mongo:8.0-rc-jammy
    env_file:
      - .env
    container_name: ff-mongodb
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    # command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    volumes:
      - ./ffdb:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s 

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    env_file:
    - .env
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@db:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      db:
        condition: service_healthy

  next-app:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: ff-next-mongo
    env_file:
      - .env
    ports:
      - "3120:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@db/${MONGO_INITDB_DATABASE}?authSource=admin
    depends_on:
      db:
        condition: service_healthy
volumes:
  ffdb: